name: rkm_env
channels:
    - conda-forge
dependencies:
  - python=3.7
  - pip
  - nodejs=14.7.0 #then npm install -g vega-lite@4.14.1 vega-cli@5.13.0 canvas@2.6.1
  - pip:
    - -r requirements.txt
