name: rkm_env
channels:
    - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1g
  - pip=20.0.2=py36_3
  - python=3.7
  - readline=7.0
  - setuptools=46.4.0
  - sqlite=3.31.1
  - tk=8.6.8
  - vega-cli
  - vega-lite-cli
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - jpeg=8d
  - giflib=5.2.1
  - nodejs=14.7.0 #then npm install -g vega-lite@4.14.1 vega-cli@5.13.0 canvas@2.6.1
  - pip:
    - -r file:requirements.txt
